apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2023-10-26T01:25:50Z"
  generation: 1
  name: test
  namespace: default
  resourceVersion: "49427"
  uid: e3e90a42-a207-4959-bb59-7a8010dc9bde
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: test
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: nginx
            imagePullPolicy: Always
            name: test
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0/5 * * * *
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
