apiVersion: apps/v1
kind: Deployment
metadata:
  name: apl
  namespace: ckad00014
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        env:
          - name: NGINX_PORT
            value: "8080"
        ports:
        - containerPort: 8080
