apiVersion: v1
kind: Pod
metadata:
  name: nginx-security
spec:
  containers:
  - name: nginx-security
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false
