apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-deployment
  name: web-deployment
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
